# Set up your streams to rtsp here.
port: "8554"
streams: # Cannot rename - must leave this as is.

# direct camera stream
#  stream-x:
#    type: cam
#    source: "v4l2src device=/dev/video0 ! videoconvert ! videoscale ! video/x-raw,framerate=15/1,width=1280,height=720"
#    mountpoint: /front
#    bitrate: 500

# topic stream 
#  stream-yay:
#    type: topic
#    source: /camera/image_raw
#    mountpoint: /back
#    caps: video/x-raw,framerate=10/1,width=640,height=480
#    bitrate: 500

#  realsense-stream:
#    type: topic
#    source: /camera/fisheye1/image_raw
#    mountpoint: /main
#    caps: video/x-raw,framerate=10/1,width=640,height=480
#    bitrate: 500
  
#  map-stream: 
#    type: topic
#    source: /bebop/camera1/image_raw
#    mountpoint: /full
#    bitrate: 2000
#    caps: video/x-raw,framerate=10/1,width=800,height=600

   uav-gui: 
     type: topic
     source: /uav/gui
     mountpoint: /full
     bitrate: 500
     caps: video/x-raw,framerate=10/1,width=1920,height=1080

